services:
  - type: web
    name: critterfall
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: NODE_ENV=production npm run start
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_ORIGIN
        sync: false
