const TRAIT_CARDS = [
  {
    id: "t001",
    name: "Pebble Plating",
    emoji: "🪨",
    points: 2,
    tags: ["shell", "earth"],
    text: "Gain 1 shield.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t002",
    name: "Noodle Spine",
    emoji: "🍜",
    points: 1,
    tags: ["weird", "body"],
    text: "Draw 1 card.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t003",
    name: "Lantern Belly",
    emoji: "🏮",
    points: 3,
    tags: ["glow", "body"],
    text: "At game end, gain +1 for each Glow trait you have.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "glow", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t004",
    name: "Borrowed Beak",
    emoji: "🐦",
    points: 1,
    tags: ["beast", "mouth"],
    text: "Steal 1 random card from the next opponent.",
    immediateEffect: { type: "stealRandom" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t005",
    name: "Static Fur",
    emoji: "⚡",
    points: 2,
    tags: ["beast", "storm"],
    text: "Everyone draws 1 card.",
    immediateEffect: { type: "everyoneDraws", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t006",
    name: "Pocket Volcano",
    emoji: "🌋",
    points: 4,
    tags: ["fire", "danger"],
    text: "Discard 1 random card from the next opponent.",
    immediateEffect: { type: "discardRandomOpponent" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t007",
    name: "Polite Tentacles",
    emoji: "🐙",
    points: 2,
    tags: ["water", "weird"],
    text: "Draw 2, then discard 1.",
    immediateEffect: { type: "rummage", draw: 2, discard: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t008",
    name: "Moss Crown",
    emoji: "🌿",
    points: 2,
    tags: ["plant", "royal"],
    text: "At game end, gain +1 for each Plant trait you have.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "plant", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t009",
    name: "Glass Knees",
    emoji: "🦵",
    points: -1,
    tags: ["fragile", "body"],
    text: "Draw 3 cards.",
    immediateEffect: { type: "draw", amount: 3 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t010",
    name: "Dramatic Gills",
    emoji: "🐟",
    points: 2,
    tags: ["water", "body"],
    text: "At game end, gain +1 for each Water trait you have.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "water", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t011",
    name: "Solar Freckles",
    emoji: "☀️",
    points: 3,
    tags: ["sun", "glow"],
    text: "Draw 1 card.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t012",
    name: "Emergency Tail",
    emoji: "🦎",
    points: 2,
    tags: ["beast", "survival"],
    text: "Gain 2 shields.",
    immediateEffect: { type: "gainShield", amount: 2 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t013",
    name: "Soup Brain",
    emoji: "🧠",
    points: 2,
    tags: ["mind", "weird"],
    text: "Peek at an opponent hand. For MVP, reveal the next opponent hand to only this player in the log as card names.",
    immediateEffect: { type: "peekOpponentHand" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t014",
    name: "Tiny Cathedral",
    emoji: "⛪",
    points: 5,
    tags: ["tiny", "royal"],
    text: "No immediate effect.",
    immediateEffect: { type: "none" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t015",
    name: "Crab Math",
    emoji: "🦀",
    points: 2,
    tags: ["water", "mind"],
    text: "At game end, gain +2 if you have at least 4 unique tags.",
    immediateEffect: { type: "none" },
    endEffect: { type: "uniqueTagBonus", threshold: 4, amount: 2 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t016",
    name: "Magnet Snout",
    emoji: "🧲",
    points: 1,
    tags: ["metal", "mouth"],
    text: "Steal 1 random card from the next opponent.",
    immediateEffect: { type: "stealRandom" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t017",
    name: "Velvet Armor",
    emoji: "🛡️",
    points: 3,
    tags: ["shell", "soft"],
    text: "Gain 1 shield. At game end, unused shields are worth +1 each.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: { type: "shieldBonus", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t018",
    name: "Echo Eyes",
    emoji: "👁️",
    points: 2,
    tags: ["mind", "sound"],
    text: "Draw 1 card. At game end, gain +1 for each Mind trait.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: { type: "tagBonus", tag: "mind", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t019",
    name: "Spare Skeleton",
    emoji: "💀",
    points: 0,
    tags: ["bone", "survival"],
    text: "Revive a random card from the discard pile into your hand.",
    immediateEffect: { type: "reviveFromDiscard" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t020",
    name: "Thunder Pouch",
    emoji: "⛈️",
    points: 3,
    tags: ["storm", "danger"],
    text: "Discard 1 random card from the next opponent.",
    immediateEffect: { type: "discardRandomOpponent" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t021",
    name: "Jellybones",
    emoji: "🪼",
    points: -2,
    tags: ["water", "fragile"],
    text: "Draw 4 cards.",
    immediateEffect: { type: "draw", amount: 4 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t022",
    name: "Diamond Dander",
    emoji: "💎",
    points: 4,
    tags: ["glow", "shell"],
    text: "No immediate effect.",
    immediateEffect: { type: "none" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t023",
    name: "Anxious Roots",
    emoji: "🌱",
    points: 1,
    tags: ["plant", "survival"],
    text: "Draw 2 cards.",
    immediateEffect: { type: "draw", amount: 2 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t024",
    name: "Royal Fungus",
    emoji: "🍄",
    points: 3,
    tags: ["plant", "royal"],
    text: "At game end, gain +2 if you have another Royal trait.",
    immediateEffect: { type: "none" },
    endEffect: { type: "pairBonus", tag: "royal", amount: 2 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t025",
    name: "Moonlit Paws",
    emoji: "🌙",
    points: 2,
    tags: ["beast", "night"],
    text: "Draw 1 card.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 2
  },
  {
    id: "t026",
    name: "Panic Wings",
    emoji: "🪽",
    points: 1,
    tags: ["sky", "survival"],
    text: "Gain 1 shield and draw 1.",
    immediateEffect: {
      type: "composite",
      effects: [
        { type: "gainShield", amount: 1 },
        { type: "draw", amount: 1 }
      ]
    },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t027",
    name: "Library Stomach",
    emoji: "📚",
    points: 2,
    tags: ["mind", "body"],
    text: "At game end, gain +1 for each card remaining in your hand.",
    immediateEffect: { type: "none" },
    endEffect: { type: "handBonus", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t028",
    name: "Meteor Teeth",
    emoji: "☄️",
    points: 4,
    tags: ["fire", "mouth"],
    text: "Destroy the lowest-point trait controlled by the next opponent. Shields block this.",
    immediateEffect: { type: "destroyOpponentTrait" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t029",
    name: "Rubber Soul",
    emoji: "🩴",
    points: 0,
    tags: ["weird", "soft"],
    text: "Your negative point traits count as positive at game end.",
    immediateEffect: { type: "none" },
    endEffect: { type: "negativeToPositive" },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t030",
    name: "Lucky Wart",
    emoji: "🍀",
    points: 1,
    tags: ["weird", "survival"],
    text: "Play one extra Trait this turn.",
    immediateEffect: { type: "playExtra", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t031",
    name: "Fossil Hoodie",
    emoji: "🧥",
    points: 3,
    tags: ["bone", "soft"],
    text: "Gain 1 shield.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t032",
    name: "Cloud Antlers",
    emoji: "☁️",
    points: 2,
    tags: ["sky", "beast"],
    text: "At game end, gain +1 for each Sky trait.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "sky", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t033",
    name: "Spicy Blood",
    emoji: "🌶️",
    points: 2,
    tags: ["fire", "body"],
    text: "Discard 1 random card from the next opponent.",
    immediateEffect: { type: "discardRandomOpponent" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t034",
    name: "Clockwork Hooves",
    emoji: "⚙️",
    points: 3,
    tags: ["metal", "beast"],
    text: "Draw 1 card. At game end, gain +1 for each Metal trait.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: { type: "tagBonus", tag: "metal", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t035",
    name: "Invisible Hat",
    emoji: "🎩",
    points: 2,
    tags: ["mind", "weird"],
    text: "Gain 1 shield.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t036",
    name: "Screaming Leaves",
    emoji: "🍃",
    points: 2,
    tags: ["plant", "sound"],
    text: "Everyone draws 1 card.",
    immediateEffect: { type: "everyoneDraws", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t037",
    name: "Basement Sun",
    emoji: "🔆",
    points: 5,
    tags: ["sun", "glow"],
    text: "No immediate effect.",
    immediateEffect: { type: "none" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t038",
    name: "Helmet Egg",
    emoji: "🥚",
    points: 1,
    tags: ["shell", "tiny"],
    text: "Gain 2 shields.",
    immediateEffect: { type: "gainShield", amount: 2 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t039",
    name: "Gremlin Diploma",
    emoji: "🎓",
    points: 2,
    tags: ["mind", "tiny"],
    text: "Draw 2, then discard 1.",
    immediateEffect: { type: "rummage", draw: 2, discard: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t040",
    name: "Comet Parasite",
    emoji: "🪱",
    points: -1,
    tags: ["danger", "weird"],
    text: "Destroy one of your own lowest-point traits, then draw 3.",
    immediateEffect: { type: "destroyOwnForDraw", amount: 3 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t041",
    name: "Opera Lungs",
    emoji: "🎭",
    points: 2,
    tags: ["sound", "body"],
    text: "At game end, gain +1 for each Sound trait.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "sound", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t042",
    name: "Rust Blossom",
    emoji: "🥀",
    points: 3,
    tags: ["metal", "plant"],
    text: "Draw 1 card.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t043",
    name: "Blanket Hide",
    emoji: "🛏️",
    points: 2,
    tags: ["soft", "survival"],
    text: "Gain 1 shield. At game end, gain +1 for each Soft trait.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: { type: "tagBonus", tag: "soft", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t044",
    name: "Star Nostrils",
    emoji: "✨",
    points: 3,
    tags: ["glow", "mouth"],
    text: "Draw 1 card.",
    immediateEffect: { type: "draw", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t045",
    name: "Banana Horn",
    emoji: "🍌",
    points: 1,
    tags: ["weird", "mouth"],
    text: "Swap hands with the next opponent.",
    immediateEffect: { type: "swapHands" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t046",
    name: "Castle Shell",
    emoji: "🏰",
    points: 4,
    tags: ["shell", "royal"],
    text: "Gain 1 shield.",
    immediateEffect: { type: "gainShield", amount: 1 },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t047",
    name: "Bonsai Bones",
    emoji: "🦴",
    points: 2,
    tags: ["bone", "plant"],
    text: "At game end, gain +1 for each Bone trait.",
    immediateEffect: { type: "none" },
    endEffect: { type: "tagBonus", tag: "bone", amount: 1 },
    passiveEffect: null,
    quantity: 1
  },
  {
    id: "t048",
    name: "Satellite Whiskers",
    emoji: "📡",
    points: 3,
    tags: ["storm", "mind"],
    text: "Peek at the next opponent hand.",
    immediateEffect: { type: "peekOpponentHand" },
    endEffect: null,
    passiveEffect: null,
    quantity: 1
  }
];

const AGE_CARDS = [
  {
    number: 1,
    id: "a001",
    name: "Drizzle of Bad Ideas",
    emoji: "🌧️",
    text: "Everyone draws 1 card.",
    effect: { type: "everyoneDraws", amount: 1 },
    isFinal: false
  },
  {
    number: 2,
    id: "a002",
    name: "The Floor Becomes Soup",
    emoji: "🍲",
    text: "The player with the smallest board draws 2 cards.",
    effect: { type: "lowestScoreDraws", amount: 2 },
    isFinal: false
  },
  {
    number: 3,
    id: "a003",
    name: "Meteor Tuesday",
    emoji: "☄️",
    text: "The player with the highest current board points discards 1 random card.",
    effect: { type: "highestScoreDiscardsRandom" },
    isFinal: false
  },
  {
    number: 4,
    id: "a004",
    name: "Tiny Ice Age",
    emoji: "🧊",
    text: "Everyone gains 1 shield.",
    effect: { type: "shieldStorm", amount: 1 },
    isFinal: false
  },
  {
    number: 5,
    id: "a005",
    name: "Moon Gets Weird",
    emoji: "🌕",
    text: "Reverse turn order this Age.",
    effect: { type: "reverseTurnOrder" },
    isFinal: false
  },
  {
    number: 6,
    id: "a006",
    name: "Snackquake",
    emoji: "🍪",
    text: "Everyone discards 1 random card unless they spend 1 shield.",
    effect: { type: "allPlayersDiscardRandom", shieldable: true },
    isFinal: false
  },
  {
    number: 7,
    id: "a007",
    name: "Double Rainbow Mutation",
    emoji: "🌈",
    text: "The next Trait played this Age has double printed points.",
    effect: { type: "doubleNextTraitPointsThisAge" },
    isFinal: false
  },
  {
    number: 8,
    id: "a008",
    name: "The Sky Has Teeth",
    emoji: "🦷",
    text: "Each player loses their lowest-point Trait unless they spend 1 shield.",
    effect: { type: "destroyLowestPointTrait", shieldable: true },
    isFinal: false
  },
  {
    number: 9,
    id: "a009",
    name: "Final Age: The Great Quiet",
    emoji: "🌑",
    text: "The world ends. Count final scores.",
    effect: { type: "finalScoring" },
    isFinal: true
  }
];

module.exports = {
  AGE_CARDS,
  TRAIT_CARDS
};
